FROM node:18-alpine

# Create an app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Set environment variables
ENV DB_URI=mongodb+srv://Shobi:Shobi2000@course-service.8eivznc.mongodb.net/Coursedb?retryWrites=true&w=majority&appName=course-service \
    JWT_SECRET=HalaMadrid

EXPOSE 7000

CMD npm start
